// <auto-generated />
using Microsoft.AspNetCore.Components;
using ProgrammersInside.Web.Core.UserContext.CoreInterfaces;
using ProgrammersInside.Web.Core.UserContext.Models;

namespace ProgrammersInside.Web.Components.Pages
{
    public partial class Home : ComponentBase
    {
        [Inject] IUserProvider UserProvider {get; set;} = null!;

        List<User> Users {get; set;}

        protected override void OnInitialized()
        {
            
            Users = UserProvider.GetAllUsers();
        }
    }
}