// <auto-generated />
using Microsoft.AspNetCore.Components;
using ProgrammersInside.Web.Core.UserContext.CoreInterfaces;
using ProgrammersInside.Web.Core.UserContext.Models;

namespace ProgrammersInside.Web.Components.Pages
{
    public partial class Home : ComponentBase
    {
        [Inject] IUserProvider UserProvider {get; set;} = null!;

        List<User> users {get; set;}

        protected override void OnInitialized()
        {
            users = new List<User>(){
                new User{
                    Name = "Test",
                    Email = "test@test",
                    Password = "test"
                }
            };
            // TODO: call users from db when we have some data
            //UserProvider.GetAllUsers();
        }
    }
}