// <auto-generated />

using Microsoft.AspNetCore.Components;
using MudBlazor;
using ProgrammersInside.Web.Core.UserContext.CoreInterfaces;
using ProgrammersInside.Web.Core.UserContext.Models;

namespace ProgrammersInside.Web.Components.Pages
{
    public partial class Register
    {
        [Inject] private NavigationManager NavigationManager { get; set; } = null!;
        [Inject] IUserProvider UserProvider { get; set; } = null!;
        private MudForm form;
        
        
        private string Email { get; set; } = null;
        private string Password { get; set; } = null;
        private string Name { get; set; } = null;
        private DateTime? Dob { get; set; } = DateTime.Today.AddYears(-18);
        private string Gender { get; set; } = null;
        private string PlayAt { get; set; } = null;
        private string FavoriteGame { get; set; } = null;
        
        private bool IsPasswordShow { get; set; }
        private InputType PasswordInput { get; set; } = InputType.Password;
        private string PasswordInputIcon { get; set; } = Icons.Material.Filled.VisibilityOff;
        private string[] GenderOptions { get; set; } = new string[] { "Masculino", "Feminino", "Outro" };
        private string[] PlayAtOptions { get; set; } = new string[] { "Celular", "Video Game", "PC" };
        private string[] FavoriteGameOptions { get; set; } = new string[] { "Free Fire", "Roblox", "Outro" };
        private string Error { get; set; } = string.Empty;

        private void ShowPassword()
        {
            if (IsPasswordShow)
            {
                IsPasswordShow = false;
                PasswordInputIcon = Icons.Material.Filled.VisibilityOff;
                PasswordInput = InputType.Password;
            }
            else
            {
                IsPasswordShow = true;
                PasswordInputIcon = Icons.Material.Filled.Visibility;
                PasswordInput = InputType.Text;
            }
        }

        private void RegisterUser()
        {
            if (!form.IsValid)
                return;
            
            UserProvider.AddUser(new User
            {
                Email = Email,
                Password = Password,
                Name = Name,
                Dob = Dob.Value,
                Gender = Gender,
                FavoriteGame = FavoriteGame,
                PlayAt = PlayAt,
            });

            NavigationManager.NavigateTo("/home");
        }
    }
}